app/__init__.py
"""Initialize Flask app."""

from flask import Flask, render_template
from flask_wtf.csrf import CSRFProtect
from pathlib import Path

import app.adapters.repository as repo

from app.adapters.memory_repository import MemoryRepository, populate


def create_app(test_config=None):
    app = Flask(__name__)


    csrf = CSRFProtect()
    csrf.init_app(app)

    
    app.config.from_object('config.DevConfig')


    # Data Path load data
    data_path = Path('app') / 'adapters' / 'data'

    if test_config is not None:
        app.config.from_mapping(test_config)
        data_path = app.config['TEST_DATA_PATH']

    # loads the memory repo
    repo.repo_instance = MemoryRepository()
    populate(data_path, repo.repo_instance)

    with app.app_context():
        from app.blueprints.app_blueprints import app_blueprint
        app.register_blueprint(app_blueprint)

    return app

app/blueprints/app_blueprints.py
import random as rand
from flask import Blueprint, redirect, render_template, url_for, session
from flask_wtf import FlaskForm
from wtforms import SubmitField,StringField,SubmitField,TextAreaField, HiddenField, SubmitField,IntegerField
from wtforms.validators import DataRequired, Length, ValidationError,NumberRange

import app.blueprints.services as services
import app.adapters.repository as repo

app_blueprint = Blueprint('app_blueprint', __name__)



@app_blueprint.route('/')
def home():
    start_index = 0
    end_index = 40
    # just gets all at the moment
    posts = services.get_posts(repo.repo_instance, start_index, end_index)
    return render_template("home.html", posts=posts)

@app_blueprint.route('/trading')
def trading():
    return render_template("trading.html")

app/blueprints/services.py
"""use for all services!"""

from app.adapters.repository import AbstractRepository


def get_posts(repo, start_idnex, end_index):
    return repo.get_posts(start_idnex,end_index)
    

app/templates/home.html
{% extends 'layout.html' %} {% block content %}

<!DOCTYPE html>
<html lang="en">
<head>

    <title>Home</title>
    <link rel="stylesheet" href={{ url_for("static", filename="css/home.css")}} />

</head>
<body>

    <!-- cards  -->
    <section class="cards">
        
        {% for post in posts %}
        
        <artical class = "card">
                <img class = "card-img" src="{{ url_for("static", filename="not_found.svg") }}" alt="img" >
            <div class = "container">
                <p>{{ post.title }}</p>
                <p>{{ post.description }}</p>
            </div>
        </artical>
        {% endfor %}

    </section>

</body>
</html>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={{ url_for("static", filename="css/base.css")}}>
    <link rel="icon" href={{ url_for("static", filename="hammer.png")}}>
    <link rel="apple-touch-icon" sizes="128x128" {{ url_for("static", filename="hammer.png")}}>


    <title>Scraps NZ</title>

</head>
<body>
    <div class ="navbar-Logo"> 
        <img src={{ url_for("static", filename="hammer.png")}} id="blink" height="50">
    </div>

    <ul class = "navbar">
        
        
        <li><a class="items_of_menus" href={{ url_for("app_blueprint.home") }}>Home</a></li>
        <li><a class="items_of_menus" href={{ url_for("app_blueprint.trading") }}>Trading</a></li>


        <!-- <li><a href="/trading.html" >Trading</a> </li> -->
        <li><a href="/help.html" >Help</a></li>

        
        
    </ul>


    <h1 class = "title">trading thingy</h1>
    
    <br><br><br><br><br><br>


    {% block content %} {% endblock %}

</body>
</html>

app/templates/trading.html
{% extends 'layout.html' %} {% block content %}

<!DOCTYPE html>
<html lang="en">
<head>

    <title>Home</title>

    <link rel="stylesheet" href={{ url_for("static", filename="css/home.css")}} />

</head>
<body>
    <h1>This is trading that extends layout </h1>

    
</body>
</html>
{% endblock %}